apiVersion: v1
kind: ConfigMap
metadata:
  name: ssts-config
  namespace: ssts
data:
  ssts.yaml: |
    # SSTS Configuration File
    server:
      address: "0.0.0.0"
      port: 8080
      read_timeout: "30s"
      write_timeout: "30s"
      tls:
        enabled: false
      cors:
        allow_origins: ["*"]
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allow_headers: ["*"]
    
    database:
      type: "postgres"
      host: "postgres-service"
      port: 5432
      username: "ssts"
      password: "ssts_password"
      database: "ssts"
      ssl_mode: "disable"
    
    influxdb:
      url: "http://influxdb-service:8086"
      token: "admin-token"
      org: "ssts"
      bucket: "metrics"
    
    redis:
      address: "redis-service:6379"
      password: ""
      db: 0
    
    log:
      level: "info"
      format: "json"
      output: "stdout"
    
    safety:
      global_limits:
        max_cpu_percent: 80.0
        max_memory_percent: 70.0
        max_disk_percent: 90.0
        emergency_stop_threshold: 95.0
      monitoring:
        check_interval: "1s"
        alert_threshold: 85.0
        auto_stop_enabled: true
      ramp_up:
        enabled: true
        duration: "30s"
        steps: 10
      emergency_stop: true
    
    auth:
      enabled: false
      jwt_secret: ""
      token_expiry: "24h"
      refresh_expiry: "168h"
    
    metrics:
      enabled: true
      collection_interval: "1s"
      batch_size: 1000
      flush_interval: "5s"
      retention:
        realtime: "24h"
        hourly_aggregates: "720h"
        daily_aggregates: "8760h"
        archive: "43800h"