apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - ssts-deployment.yaml
  - postgres-statefulset.yaml
  - influxdb-statefulset.yaml
  - redis-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: ssts
  app.kubernetes.io/version: "1.0.0"